*******************************************************************************
****** CurrentSource_All_ST schematic Stimulator_IMP  <vs>  CurrentSource_All_ST layout Stimulator_IMP
*******************************************************************************

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(AND2HDX0) Cell                                   5       5           5       5
(CurrentMirror_ST) Cell                           1       1           1       1
(Ext_Iref_ST) Cell                                1       1           1       1
(IN_3VX2) Cell                                    5       5           5       5
(Idac_5bit_ST_V3) Cell                            1       1           1       1
(LSHVT18U3VX1) Cell                               5       5           5       5

Match Statistics
================                                  Total             Unmatched
Cell/Device                               schematic  layout   schematic  layout
(AND2HDX0) Cell                                   5       5           0       0
(CurrentMirror_ST) Cell                           1       1           0       0
(Ext_Iref_ST) Cell                                1       1           0       0
(IN_3VX2) Cell                                    5       5           0       0
(Idac_5bit_ST_V3) Cell                            1       1           0       0
(LSHVT18U3VX1) Cell                               5       5           0       0
                                             ------  ------      ------  ------
Total                                            18      18           0       0

Match Statistics for Nets                        25      25           0       0

=========================================================[CurrentSource_All_ST]
====== Unbound Pin ============================================================
===============================================================================

S Mag0_ST
S Mag1_ST
S Mag2_ST
S Mag3_ST
S Mag4_ST
S vdd3!

=========================================================[CurrentSource_All_ST]
====== Summary of Errors ======================================================
===============================================================================

Schematic  Layout     Error Type
---------  ------     ----------
 6          -         Unbound Pin

